### ISSUE TITLE
[Question] Questions about handle an assertion example

### ISSUE THREAD

**Issue by mjxdev** [mrtristan/CoreSaml2Utils#3]
Thank you for your work on this fantastic package.
I've started using it yesterday and I have a few questions.

1. `assertionParser.LoadIdpPublicKey(config.CertificateBody);`

- To which certificate does CertificateBody refer to ? 
- Why is it stored in config  ?

2. `assertionParser.IsValid(expectedAudience: "https://your-issuer-url.com/saml2",)`

- Is it possible to add a second parameter for a certificate instead of loading it using `LoadIdpPublicKey` ?

3. `assertionParser.DecryptIfNeeded(cert);`

- When do we need this method ?
It doesn't return anything or affect a global variable.

**Comment by mrtristan** [comment]
@mjxdev valid questions. i have some cleaning up to do of that example and the repo in general.

1 - the idp cert is something that should really be preconfigured on your side. When the assertion comes through you can use the issuer of the assertion to go get the corresponding cert from your db or config or wherever you're storing those configs. that config object is coming from my database

2 - yea i kept some of the original library's approach regarding the initialization of the assertion parsing class. it needs to be cleaned up in a few areas when i can get around to doing so.

3 - this should become more of an internal method in the parser. it literally does what it says in that if the assertion is encrypted it will decrypt it so that you can interact with it with the subsequent methods.

**Comment by mjxdev** [comment]
Thank you for such a prompt and detailed answer. I really appreciate it.
